version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/dashboard
      - REDIS_URL=redis://redis:6379
      - RUST_LOG=debug
      - SERVER_PORT=8080
    volumes:
      - .:/app
      - cargo-cache:/usr/local/cargo/registry
    depends_on:
      - postgres
      - redis
    command: cargo watch -x run
    networks:
      - dashboard-network

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dashboard
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - dashboard-network

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - dashboard-network

networks:
  dashboard-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data:
  cargo-cache: 