max_width = 100
tab_spaces = 4
edition = "2021"
reorder_imports = true
imports_granularity = "Module"
use_field_init_shorthand = true
use_small_heuristics = "Max"
format_code_in_doc_comments = true
wrap_comments = true
comment_width = 100
normalize_comments = true
normalize_doc_attributes = true 